spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://config-service:8071/
  main:
    web-application-type: reactive

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka}