server:
  port: 8081

spring:
  application:
    name: battle-service

  datasource:
    url: jdbc:postgresql://localhost:5432/battle-game-service
    username: postgres
    password: 77553300

    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

  liquibase:
    change-log: classpath:db_changelog_master.xml