server:
  port: 8081

spring:
  application:
    name: battle-service
  cloud:
    loadbalancer:
    ribbon.enabled: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      show_sql: true
    generate:
      ddl: true
    hibernate:
      ddl-auto: none

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka