eureka:
  eureka:
    instance:
      preferIpAddress: true
  client:
    fetchRegistry: false
    registerWithEureka: false

server:
  port: 8761

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    config:
      enabled: false

application:
  name: discovery-service