server:
  port: 8081
keystore:
  path: keystore/battle-service.jks
  password: password
  keypair-name: battle-service

spring:
  application:
    name: authentication-service
  config:
    import: optional:configserver:http://config-service:8071/

security:
  jwt:
    publicKey: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4Tn0fmXURxmQ9Fh1KFRfR06AinxS8sW8ydXC+p1U9+SKf+y4u6J1zgXwMFVu/eZ8jLOj5NtRnIcrNwFWgu4mRCU8eyE0kh1P2jyZLa+nHuJdnVQYwgBjjeKXVZmGqtHoqqLaATfAuifpvuCS9BeIJFEn2/hlwb5D6DCnmBzt8UKOKArpw6xcWNuwUtwXyNXEA5IqHREv2fKxA3FKLu3OME4CQBEfrLjdF2/HcWY8nW4K1k4ezIVPS40ngc53gYSatVBHjOyxqBc30wSMK09Pk2WY8ZPpVsk9Eic0gk9C7WHHOkCcu6pR7iu34xGn1UAMwDIq2ZmGY8Y/UGDHNChdBQIDAQAB-----END PUBLIC KEY-----
