spring:
  application:
    name: audit-service
  datasource:
    url: jdbc:postgresql://localhost:5432/battle-audit-service
    username: postgres
    password: 77553300
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
  cloud:
    config:
      enabled: false
  liquibase:
    change-log: classpath:db_changelog_master.xml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true