spring:
  application:
    name: authentication-service

  datasource:
    url: jdbc:postgresql://localhost:5432/battle-user-service
    username: postgres
    password: 77553300

    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka