spring:
  application:
    name: statistics-service
  datasource:
    url: jdbc:postgresql://localhost:5432/battle-statistic-service
    username: postgres
    password: 77553300
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
  liquibase:
    change-log: classpath:db_changelog_master.xml

eureka:
  instance:
    preferIpAddress: true