spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres:5432/battle-user-service
    username: postgres
    password: 77553300
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
  liquibase:
    change-log: classpath:db_changelog_master.xml

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka}

security:
  jwt:
    publicKey: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4Tn0fmXURxmQ9Fh1KFRfR06AinxS8sW8ydXC+p1U9+SKf+y4u6J1zgXwMFVu/eZ8jLOj5NtRnIcrNwFWgu4mRCU8eyE0kh1P2jyZLa+nHuJdnVQYwgBjjeKXVZmGqtHoqqLaATfAuifpvuCS9BeIJFEn2/hlwb5D6DCnmBzt8UKOKArpw6xcWNuwUtwXyNXEA5IqHREv2fKxA3FKLu3OME4CQBEfrLjdF2/HcWY8nW4K1k4ezIVPS40ngc53gYSatVBHjOyxqBc30wSMK09Pk2WY8ZPpVsk9Eic0gk9C7WHHOkCcu6pR7iu34xGn1UAMwDIq2ZmGY8Y/UGDHNChdBQIDAQAB-----END PUBLIC KEY-----
