spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

eureka:
  instance:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8071