spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

eureka:
  instance:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka}

server:
  port: 8071