eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
application:
  name: eureka-server

server:
  port: 8761